apiVersion: v1
kind: Secret
metadata:
  name: dsh-proxy-auth
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: dsh
type: Opaque
stringData:
  PROXY_USERNAME: {{ .Values.olaresEnv.PROXY_USERNAME | default "" | quote }}
  PROXY_PASSWORD: {{ .Values.olaresEnv.PROXY_PASSWORD | default "" | quote }}